### ISSUE TITLE
(void-function nrepl-current-connection-buffer)

### ISSUE THREAD

**Issue by bard** [clojure-emacs/squiggly-clojure#42]
- cider 0.12.0 from melpa-stable
- flycheck-clojure 0.1.3 from melpa-stable
- GNU Emacs 24.5.1

After loading .clj file and issuing `M-x cider-jack-in`, I get:

```
Error while checking syntax automatically: (void-function nrepl-current-connection-buffer)
```

If I install flycheck-clojure from github, the error disappears. Maybe just an out of date package?

**Comment by pnf** [comment]
Ah yes...  When we made this change to be compatible with cider, I didn't tag it, because at the time the name change hadn't made it on the cider side to `melpa-stable`.  Then I forgot about it.  Anyway, I've tagged the latest from github as `0.1.5`, so it should hit `melpa-stable` shortly.  In the mean time, you can always get the latest from plain `melpa`.

**Comment by bard** [comment]
:+1: Thank you!
